Minor updates to rituals workflow (#83)

diff --git a/.github/workflows/call-rituals.yaml b/.github/workflows/call-rituals.yaml
--- a/.github/workflows/call-rituals.yaml
+++ b/.github/workflows/call-rituals.yaml
@@ -73,7 +73,7 @@ jobs:
         if: ${{ github.event_name == 'push' && contains(github.ref, '/rc-v') }}
         run: |
           Rscript -e 'pak::pkg_install("r-lib/urlchecker"); urlchecker::url_update()'
-          git add . && git commit -m 'Update links (GitHub Actions)' || echo "No link changes to commit"
+          git add -u && git commit -m 'Update links (GitHub Actions)' || echo "No link changes to commit"
 
       - name: Document
         run: |
@@ -144,7 +144,7 @@ jobs:
           if [ -n "`git cherry origin/HEAD`" ]; then
             echo "Un-pushed commits:"
             git cherry -v origin/HEAD
-            echo "\nShould not push to HEAD branch. Please make a PR to have changes be collected. Exiting"
+            echo "::error:: Should not push to HEAD branch. Please make a PR to have changes be collected. Exiting"
             exit 1
           fi
 
