try using an external github push

diff --git a/.github/workflows/shinytest.yml b/.github/workflows/shinytest.yml
--- a/.github/workflows/shinytest.yml
+++ b/.github/workflows/shinytest.yml
@@ -108,16 +108,17 @@ jobs:
         run: >
           Rscript -e "shinycoreci::test_shinytest(dir = 'apps')"
 
-      # - name: Determine if test failed
-      #   if: failure()
-      #   id: shinytest_failed
-      #   run: |
-      #     echo "::set-output name=horribly::1"
+      - name: Determine if test failed
+        if: failure()
+        id: shinytest_failed
+        run: |
+          echo "::set-output name=horribly::1"
 
       - name: Commit files
-        # if: steps.shinytest_failed.outputs.horribly
-        if: failure()
+        if: steps.shinytest_failed.outputs.horribly
+        # if: failure()
         shell: bash
+        # git push https://schloerke:${{secrets.GH_PAT}}@github.com/rstudio/shinycoreci-apps.git HEAD:${{ github.sha }}-${{ runner.os }} || echo "No changes to push"
         run: |
           cd apps
           git config --local user.email "action@github.com"
@@ -126,7 +127,16 @@ jobs:
           git commit -m "GitHub Actions changes" || echo "No changes to commit"
           git status
           git log --graph -n 5
-          git push https://schloerke:${{secrets.GH_PAT}}@github.com/rstudio/shinycoreci-apps.git HEAD:${{ github.sha }}-${{ runner.os }} || echo "No changes to push"
+
+      - name: Push files
+        if: steps.shinytest_failed.outputs.horribly
+        uses: ad-m/github-push-action@master
+        with:
+          directory: apps
+          github_token: ${{ secrets.GH_PAT }}
+          repository: rstudio/shinycoreci-apps
+          branch: ${{ github.sha }}-${{ runner.os }}
+          force: true
 
       - name: Fix path for Windows caching
         if: runner.os == 'Windows'
